print(1)
raise ValueError
print(2)
# You need to specify the type of the exception raised.

# ********************************************************
name = "12345"
raise NameError("Invalid name!")